version: "3.1"

services:
  php:
    image: php:8.0-apache
    volumes:
      - php:/rw
  web:
    image: nginx
    depends_on:
      - php
    ports:
      - "9999:80"
    volumes:
      - nginx:/etc/nginx/conf.d:ro
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: user
        MYSQL_DATABASE: lumen
        MYSQL_USER: user
        MYSQL_PASSWORD: root
    ports:
        - "8000:3306"
  phpmyadmin:
    image: phpmyadmin
    ports:
        - "8080:80"
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
        - db
  composer:
    image: composer:2.0.12
    command: install
    volumes:
      - .:/app

volumes:
  php: {}
  db_data: {}
  nginx: {}

